# Generated by Django 5.0 on 2024-01-23 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="coordinates",
        ),
    ]
